[package]
name = "xml"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5.13"
encoding_rs = "0.8.22"
encoding_rs_io = "0.1.7"
roxmltree = "0.14.1"
quick-xml = "0.22.0"